import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {Building2,LayoutDashboard,Users,DoorOpen,Receipt,WalletCards,Gauge,CalendarClock,UserRound,FileText,Settings,LogOut,RefreshCw,Plus,Search,Printer,X} from "lucide-react";
import {supabase,supabaseConfigurationError} from "./supabase";
import "./styles.css";

const money=n=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0}).format(Number(n||0));
const monthStart=()=>new Date().toISOString().slice(0,7)+"-01";
const today=()=>new Date().toISOString().slice(0,10);

function Auth(){
 const [mode,setMode]=useState("signin"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[sent,setSent]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);setError("");setSent(false);try{const r=mode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)throw r.error;if(mode==="signup"&&!r.data.session)setSent(true)}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
 return <div className="auth"><div className="authcard"><div className="brand"><Building2/><b>RentFlow</b></div><h1>{mode==="signin"?"Welcome back":"Create your account"}</h1><p className="muted">Property management, rent collection and tenant records in one workspace.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength="6"/></label>{error&&<div className="errorbox">{error}</div>}{sent&&<div className="success">Account created. Check your email to confirm your account.</div>}<button className="primary" disabled={busy}>{busy?"Please wait…":mode==="signin"?"Sign in":"Create account"}</button></form><button className="linkbtn" onClick={()=>{setMode(mode==="signin"?"signup":"signin");setError("")}}>{mode==="signin"?"Create a new account":"Already have an account? Sign in"}</button></div></div>
}
function ConfigError(){return <div className="auth"><div className="authcard"><div className="brand"><Building2/><b>RentFlow</b></div><h1>Configuration required</h1><p className="muted">Supabase frontend configuration is missing or invalid.</p><div className="errorbox"><b>Required:</b><br/>VITE_SUPABASE_URL<br/>VITE_SUPABASE_PUBLISHABLE_KEY<br/><br/>{supabaseConfigurationError}</div></div></div>}
function Onboarding({user,onDone}){const [name,setName]=useState(""),[location,setLocation]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");async function create(e){e.preventDefault();setBusy(true);try{const r=await supabase.from("properties").insert({owner_id:user.id,name,location}).select().single();if(r.error)throw r.error;const m=await supabase.from("property_members").insert({property_id:r.data.id,user_id:user.id,role:"owner"});if(m.error)throw m.error;onDone()}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}return <div className="auth"><div className="authcard"><div className="brand"><Building2/><b>RentFlow</b></div><h1>Set up your property</h1><p className="muted">Create your first property workspace.</p><form onSubmit={create}><label>Property name<input value={name} onChange={e=>setName(e.target.value)} required placeholder="e.g. Riverside Apartments"/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)}/></label>{error&&<div className="errorbox">{error}</div>}<button className="primary" disabled={busy}>{busy?"Creating…":"Create property"}</button></form></div></div>}

const nav=[["dashboard","Dashboard",LayoutDashboard],["tenants","Tenants",Users],["units","Units",DoorOpen],["invoices","Invoices",Receipt],["payments","Payments",WalletCards],["utilities","Utilities",Gauge],["leases","Leases",CalendarClock],["owners","Owners",UserRound],["reports","Reports",FileText],["settings","Settings",Settings]];
const emptyData=()=>({units:[],tenants:[],invoices:[],payments:[],allocations:[],leases:[],readings:[],owners:[],expenses:[]});

function App(){
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[property,setProperty]=useState(null),[page,setPage]=useState("dashboard"),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[data,setData]=useState(emptyData());
 useEffect(()=>{if(!supabase){setLoading(false);return}let active=true;supabase.auth.getSession().then(({data,error})=>{if(active){if(error)setMessage(error.message);setSession(data?.session||null);setLoading(false)}});const {data:s}=supabase.auth.onAuthStateChange((_e,x)=>{if(active)setSession(x)});return()=>{active=false;s.subscription.unsubscribe()}},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){setLoading(true);const p=await supabase.from("properties").select("*").order("created_at").limit(1);if(p.error){setMessage(p.error.message);setLoading(false);return}if(!p.data?.length){setProperty(null);setData(emptyData());setLoading(false);return}setProperty(p.data[0]);await refresh(p.data[0].id);setLoading(false)}
 async function refresh(id=property?.id){if(!id)return;const q=await Promise.all([supabase.from("units").select("*").eq("property_id",id).order("label"),supabase.from("tenants").select("*").eq("property_id",id).order("full_name"),supabase.from("invoices").select("*").eq("property_id",id).order("billing_month",{ascending:false}),supabase.from("rent_payments").select("*").eq("property_id",id).order("payment_date",{ascending:false}),supabase.from("payment_allocations").select("*").eq("property_id",id),supabase.from("leases").select("*").eq("property_id",id).order("end_date"),supabase.from("meter_readings").select("*").eq("property_id",id).order("reading_date",{ascending:false}),supabase.from("owners").select("*").eq("property_id",id),supabase.from("owner_expenses").select("*").eq("property_id",id).order("expense_date",{ascending:false})]);setData({units:q[0].data||[],tenants:q[1].data||[],invoices:q[2].data||[],payments:q[3].data||[],allocations:q[4].data||[],leases:q[5].data||[],readings:q[6].data||[],owners:q[7].data||[],expenses:q[8].data||[]})}
 async function generateInvoices(){const r=await supabase.rpc("generate_monthly_invoices",{p_property_id:property.id,p_billing_month:monthStart()});setMessage(r.error?r.error.message:String(r.data?.created||0)+" invoices generated for "+monthStart().slice(0,7));await refresh()}
 async function signout(){await supabase.auth.signOut();setProperty(null);setData(emptyData())}
 if(!supabase)return <ConfigError/>;if(loading)return <div className="loading"><RefreshCw className="spin"/>Loading RentFlow…</div>;if(!session)return <Auth/>;if(!property)return <Onboarding user={session.user} onDone={load}/>;
 return <Shell page={page} setPage={setPage} query={query} setQuery={setQuery} property={property} data={data} refresh={refresh} message={message} setMessage={setMessage} generateInvoices={generateInvoices} signout={signout}/>
}

function Shell(p){const C=({dashboard:Dashboard,tenants:Tenants,units:Units,invoices:Invoices,payments:Payments,utilities:Utilities,leases:Leases,owners:Owners,reports:Reports,settings:SettingsPage}[p.page]||Dashboard);return <div className="app"><aside><div className="brand"><Building2/><b>RentFlow</b></div><div className="propertymini">{p.property.name}<small>{p.property.location||"Property"}</small></div>{nav.map(([id,label,I])=><button key={id} className={p.page===id?"navactive":""} onClick={()=>p.setPage(id)}><I/>{label}</button>)}<div className="sidebottom"><button onClick={()=>p.refresh()}><RefreshCw/>Refresh</button><button onClick={p.signout}><LogOut/>Sign out</button></div></aside><main><header><div><h2>{nav.find(x=>x[0]===p.page)?.[1]}</h2><small>{p.property.currency||"KES"} · {p.property.location||""}</small></div><div className="search"><Search/><input value={p.query} onChange={e=>p.setQuery(e.target.value)} placeholder="Search…"/></div></header><section>{p.message&&<div className="notice">{p.message}<button onClick={()=>p.setMessage("")}><X/></button></div>}<C {...p}/></section></main></div>}

function Dashboard({data,generateInvoices}){const m=monthStart(),inv=data.invoices.filter(x=>x.billing_month===m),billed=inv.reduce((s,x)=>s+Number(x.total||0),0),paid=data.payments.filter(x=>String(x.payment_date||"").startsWith(m.slice(0,7))).reduce((s,x)=>s+Number(x.amount||0),0),occupied=data.units.filter(x=>x.status==="occupied").length,outstanding=inv.reduce((s,i)=>s+Math.max(0,Number(i.total||0)-data.allocations.filter(a=>a.invoice_id===i.id).reduce((x,a)=>x+Number(a.amount||0),0)),0);return <><div className="pagehead"><div><h1>Portfolio overview</h1><p>Monitor rent, occupancy, invoices and arrears.</p></div><button className="primary" onClick={generateInvoices}><Receipt/>Generate monthly invoices</button></div><div className="cards"><Card label="Billed this month" value={money(billed)}/><Card label="Collected" value={money(paid)}/><Card label="Outstanding" value={money(outstanding)}/><Card label="Occupancy" value={(data.units.length?Math.round(occupied/data.units.length*100):0)+"%"} sub={data.units.filter(x=>x.status==="vacant").length+" vacant"}/></div><div className="grid2"><Panel title="Collection"><Stat label="Invoices" value={inv.length}/><Stat label="Paid" value={inv.filter(x=>x.status==="paid").length}/><Stat label="Partial" value={inv.filter(x=>x.status==="partially_paid").length}/><Stat label="Overdue" value={inv.filter(x=>x.status!=="paid"&&x.status!=="void"&&x.due_date<today()).length}/></Panel><Panel title="Portfolio"><Stat label="Units" value={data.units.length}/><Stat label="Active tenants" value={data.tenants.filter(x=>x.status==="active").length}/><Stat label="Leases ending ≤90 days" value={data.leases.filter(x=>x.end_date&&new Date(x.end_date)<=new Date(Date.now()+90*86400000)&&x.renewal_status!=="renewed").length}/></Panel></div></>}
function Card({label,value,sub}){return <div className="card"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Stat({label,value}){return <div className="stat"><span>{label}</span><b>{value}</b></div>}
function Panel({title,children}){return <div className="panel"><div className="paneltitle"><h2>{title}</h2></div>{children}</div>}
function Toolbar({title,onAdd,actionLabel="Add"}){return <div className="pagehead"><div><h1>{title}</h1><p>Manage your {title.toLowerCase()}.</p></div>{onAdd&&<button className="primary" onClick={onAdd}><Plus/>{actionLabel}</button>}</div>}
function Field({label,value,onChange,type="text",required=false}){return <label>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}
function Table({heads,rows}){return <div className="table"><div className="thead">{heads.map(h=><span key={h}>{h}</span>)}</div>{rows.length?rows.map((r,i)=><div className="tr" key={i}>{r.map((v,j)=><span key={j}>{v}</span>)}</div>):<div className="empty">No records found.</div>}</div>}

function Tenants({data,property,refresh,query}){const [open,setOpen]=useState(false),[f,setF]=useState({full_name:"",phone:"",id_number:"",rent:"",deposit:"",unit_id:""});async function save(e){e.preventDefault();const r=await supabase.from("tenants").insert({...f,property_id:property.id,rent:Number(f.rent||0),deposit:Number(f.deposit||0),unit_id:f.unit_id||null});if(r.error)return alert(r.error.message);setOpen(false);await refresh()}const rows=data.tenants.filter(t=>(t.full_name+" "+(t.phone||"")+" "+(t.id_number||"")).toLowerCase().includes(query.toLowerCase()));return <><Toolbar title="Tenants" onAdd={()=>setOpen(!open)}/>{open&&<Panel title="Add tenant"><form className="formgrid" onSubmit={save}><Field label="Full name" value={f.full_name} onChange={v=>setF({...f,full_name:v})} required/><Field label="Phone" value={f.phone} onChange={v=>setF({...f,phone:v})}/><Field label="ID / Passport" value={f.id_number} onChange={v=>setF({...f,id_number:v})}/><Field label="Monthly rent" type="number" value={f.rent} onChange={v=>setF({...f,rent:v})}/><Field label="Deposit" type="number" value={f.deposit} onChange={v=>setF({...f,deposit:v})}/><label>Unit<select value={f.unit_id} onChange={e=>setF({...f,unit_id:e.target.value})}><option value="">Unassigned</option>{data.units.map(u=><option key={u.id} value={u.id}>{u.label}</option>)}</select></label><button className="primary">Save tenant</button></form></Panel>}<Table heads={["Tenant","Phone","Unit","Rent","Status"]} rows={rows.map(t=>[t.full_name,t.phone||"—",data.units.find(u=>u.id===t.unit_id)?.label||"—",money(t.rent),t.status||"active"])}/></>}
function Units({data,property,refresh,query}){const [open,setOpen]=useState(false),[label,setLabel]=useState(""),[rent,setRent]=useState("");async function save(e){e.preventDefault();const r=await supabase.from("units").insert({property_id:property.id,label,monthly_rent:Number(rent||0),status:"vacant"});if(r.error)return alert(r.error.message);setOpen(false);await refresh()}const rows=data.units.filter(u=>(u.label+" "+(u.status||"")).toLowerCase().includes(query.toLowerCase()));return <><Toolbar title="Units" onAdd={()=>setOpen(!open)}/>{open&&<Panel title="Add unit"><form className="formgrid"><Field label="Unit label" value={label} onChange={setLabel} required/><Field label="Monthly rent" type="number" value={rent} onChange={setRent}/><button className="primary" onClick={save}>Save unit</button></form></Panel>}<Table heads={["Unit","Rent","Status","Tenant"]} rows={rows.map(u=>[u.label,money(u.monthly_rent),u.status||"vacant",data.tenants.find(t=>t.unit_id===u.id)?.full_name||"—"])}/></>}
function Invoices({data,generateInvoices,query}){const rows=data.invoices.filter(i=>(i.invoice_number+" "+(i.status||"")+" "+(i.billing_month||"")).toLowerCase().includes(query.toLowerCase()));return <><Toolbar title="Invoices" actionLabel="Generate" onAdd={generateInvoices}/><Table heads={["Invoice","Tenant","Month","Total","Due date","Status"]} rows={rows.map(i=>[i.invoice_number||"—",data.tenants.find(t=>t.id===i.tenant_id)?.full_name||"—",i.billing_month,money(i.total),i.due_date||"—",i.status||"open"])}/></>}
function Payments({data,property,refresh,query}){const [open,setOpen]=useState(false),[f,setF]=useState({tenant_id:"",amount:"",payment_date:today(),reference:"",method:"M-Pesa"});async function save(e){e.preventDefault();const r=await supabase.from("rent_payments").insert({property_id:property.id,tenant_id:f.tenant_id,amount:Number(f.amount),payment_date:f.payment_date,reference:f.reference,payment_method:f.method});if(r.error)return alert(r.error.message);setOpen(false);await refresh()}const rows=data.payments.filter(x=>(String(x.reference||"")+" "+String(x.payment_method||"")+" "+String(x.amount||"")).toLowerCase().includes(query.toLowerCase()));return <><Toolbar title="Payments" onAdd={()=>setOpen(!open)}/>{open&&<Panel title="Record payment"><form className="formgrid"><label>Tenant<select required value={f.tenant_id} onChange={e=>setF({...f,tenant_id:e.target.value})}><option value="">Select tenant</option>{data.tenants.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label><Field label="Amount" type="number" value={f.amount} onChange={v=>setF({...f,amount:v})} required/><Field label="Payment date" type="date" value={f.payment_date} onChange={v=>setF({...f,payment_date:v})}/><Field label="Reference" value={f.reference} onChange={v=>setF({...f,reference:v})}/><Field label="Method" value={f.method} onChange={v=>setF({...f,method:v})}/><button className="primary">Save payment</button></form></Panel>}<Table heads={["Date","Tenant","Amount","Method","Reference"]} rows={rows.map(x=>[x.payment_date,data.tenants.find(t=>t.id===x.tenant_id)?.full_name||"—",money(x.amount),x.payment_method||"—",x.reference||"—"])}/></>}
function Utilities({data}){return <><Toolbar title="Utilities"/><Table heads={["Reading date","Meter","Reading","Tenant"]} rows={data.readings.map(x=>[x.reading_date,x.meter_type||"—",x.reading_value??"—",data.tenants.find(t=>t.id===x.tenant_id)?.full_name||"—"])}/></>}
function Leases({data}){return <><Toolbar title="Leases"/><Table heads={["Tenant","Start","End","Renewal"]} rows={data.leases.map(x=>[data.tenants.find(t=>t.id===x.tenant_id)?.full_name||"—",x.start_date||"—",x.end_date||"—",x.renewal_status||"pending"])}/></>}
function Owners({data}){return <><Toolbar title="Owners"/><Table heads={["Owner","Phone","Email"]} rows={data.owners.map(x=>[x.full_name||x.name||"—",x.phone||"—",x.email||"—"])}/></>}
function Reports({data}){const collected=data.payments.reduce((s,x)=>s+Number(x.amount||0),0),expenses=data.expenses.reduce((s,x)=>s+Number(x.amount||0),0);return <><div className="pagehead"><div><h1>Reports</h1><p>Portfolio-level financial summary.</p></div><button onClick={()=>window.print()}><Printer/>Print / PDF</button></div><div className="cards"><Card label="Total collected" value={money(collected)}/><Card label="Owner expenses" value={money(expenses)}/><Card label="Net collected" value={money(collected-expenses)}/><Card label="Tenants" value={data.tenants.length}/></div></>}
function SettingsPage({property}){return <><Toolbar title="Settings"/><Panel title="Property"><Stat label="Name" value={property.name}/><Stat label="Location" value={property.location||"—"}/><Stat label="Currency" value={property.currency||"KES"}/></Panel></>}

createRoot(document.getElementById("root")).render(<App/>);
