import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {Building2,LayoutDashboard,Users,DoorOpen,Receipt,WalletCards,Gauge,FileText,UserRound,MessageSquare,LogOut,Plus,RefreshCw,Search,Download,Printer,Send,Settings,CalendarClock} from "lucide-react";
import {supabase,supabaseConfigurationError} from "./supabase";
import "./styles.css";

const money=n=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0}).format(Number(n||0));
const today=()=>new Date().toISOString().slice(0,10);
const month=()=>today().slice(0,7)+"-01";
const fmtDate=d=>d?new Date(d).toLocaleDateString("en-KE",{day:"2-digit",month:"short",year:"numeric"}):"—";
const daysLate=d=>Math.max(0,Math.floor((Date.now()-new Date(d+"T00:00:00").getTime())/86400000));
const blank={full_name:"",phone:"",id_number:"",unit_id:"",rent:"",deposit:"",service_charge:"",parking:"",extras:"",lease_start:"",lease_end:"",status:"active"};

function App(){
 const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[property,setProperty]=useState(null),[page,setPage]=useState("dashboard"),[message,setMessage]=useState(""),[query,setQuery]=useState("");
 const [data,setData]=useState({units:[],tenants:[],invoices:[],payments:[],allocations:[],credits:[],leases:[],readings:[],owners:[],expenses:[],notifications:[],billing:[],mpesa:[]});
 useEffect(()=>{if(!supabase){setLoading(false);return} supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:s}=supabase.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>s.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){setLoading(true);const {data:p,error}=await supabase.from("properties").select("*").order("created_at").limit(1);if(error){setMessage(error.message);setLoading(false);return}if(!p?.length){setProperty(null);setLoading(false);return}setProperty(p[0]);await refresh(p[0].id);setLoading(false)}
 async function refresh(id=property?.id){if(!id)return;const q=await Promise.all([
  supabase.from("units").select("*").eq("property_id",id).order("label"),
  supabase.from("tenants").select("*").eq("property_id",id).order("full_name"),
  supabase.from("invoices").select("*").eq("property_id",id).order("billing_month",{ascending:false}),
  supabase.from("rent_payments").select("*").eq("property_id",id).order("payment_date",{ascending:false}),
  supabase.from("payment_allocations").select("*").eq("property_id",id),
  supabase.from("tenant_credits").select("*").eq("property_id",id).gt("remaining_amount",0),
  supabase.from("leases").select("*").eq("property_id",id).order("end_date"),
  supabase.from("meter_readings").select("*").eq("property_id",id).order("reading_date",{ascending:false}),
  supabase.from("owners").select("*").eq("property_id",id),
  supabase.from("owner_expenses").select("*").eq("property_id",id).order("expense_date",{ascending:false}),
  supabase.from("notification_logs").select("*").eq("property_id",id).order("created_at",{ascending:false}),
  supabase.from("billing_runs").select("*").eq("property_id",id).order("billing_month",{ascending:false}),
  supabase.from("mpesa_transactions").select("*").eq("property_id",id).order("created_at",{ascending:false})
 ]);setData({units:q[0].data||[],tenants:q[1].data||[],invoices:q[2].data||[],payments:q[3].data||[],allocations:q[4].data||[],credits:q[5].data||[],leases:q[6].data||[],readings:q[7].data||[],owners:q[8].data||[],expenses:q[9].data||[],notifications:q[10].data||[],billing:q[11].data||[],mpesa:q[12].data||[]})}
 const act=async(fn,ok)=>{try{const r=await fn();if(r?.error)throw r.error;setMessage(ok);await refresh()}catch(e){setMessage(e.message||String(e))}};
 async function generate(){const r=await supabase.rpc("generate_monthly_invoices",{p_property_id:property.id,p_billing_month:month()});setMessage(r.error?r.error.message:`${r.data?.created||0} invoices generated for ${month().slice(0,7)}`);await refresh()}
 async function signout(){await supabase.auth.signOut();setProperty(null)}
 if(!supabase)return <ConfigurationScreen error={supabaseConfigurationError}/>;
 if(loading)return <div className="center"><RefreshCw className="spin"/>Loading RentFlow…</div>;
 if(!session)return <Auth/>;
 if(!property)return <Onboarding user={session.user} done={load}/>;
 const nav=[
  ["dashboard","Dashboard",LayoutDashboard],["tenants","Tenants",Users],["units","Units & Vacancy",DoorOpen],["invoices","Invoices",Receipt],["payments","Payments",WalletCards],
  ["utilities","Utilities",Gauge],["leases","Leases",CalendarClock],["owners","Owners",UserRound],["reports","Reports",FileText],["notifications","Notifications",MessageSquare],["settings","Settings",Settings]
 ];
 return <div className="app"><aside><div className="brand"><Building2/><b>RentFlow</b></div>{nav.map(([id,label,I])=><button key={id} onClick={()=>setPage(id)} className={page===id?"active":""}><I/>{label}</button>)}<div className="bottom"><button onClick={()=>refresh()}><RefreshCw/>Refresh</button><button onClick={signout}><LogOut/>Sign out</button></div></aside>
 <main><header><div><strong>{property.name}</strong><small>{property.location} · {property.currency}</small></div><div className="search"><Search/><input placeholder="Search current page…" value={query} onChange={e=>setQuery(e.target.value)}/></div></header>
 <section><div className="titlebar"><div><h1>{nav.find(x=>x[0]===page)?.[1]}</h1><p>Manage your property operations from one workspace.</p></div>{page==="dashboard"&&<button onClick={generate}><Receipt/>Generate monthly invoices</button>}</div>{message&&<div className="notice">{message}<button onClick={()=>setMessage("")}>×</button></div>}
 {page==="dashboard"&&<Dashboard data={data} generate={generate}/>}
 {page==="tenants"&&<Tenants data={data} property={property} refresh={refresh} act={act} query={query}/>}
 {page==="units"&&<Units data={data} property={property} refresh={refresh} act={act} query={query}/>}
 {page==="invoices"&&<Invoices data={data} property={property} refresh={refresh} generate={generate} query={query}/>}
 {page==="payments"&&<Payments data={data} property={property} refresh={refresh} act={act} query={query}/>}
 {page==="utilities"&&<Utilities data={data} property={property} refresh={refresh} act={act}/>}
 {page==="leases"&&<Leases data={data} property={property} refresh={refresh} act={act}/>}
 {page==="owners"&&<Owners data={data} property={property} refresh={refresh} act={act}/>}
 {page==="reports"&&<Reports data={data} property={property}/>}
 {page==="notifications"&&<Notifications data={data} property={property} refresh={refresh} act={act}/>}
 {page==="settings"&&<SettingsPage property={property} data={data}/>}
 </section></main></div>
}

function Dashboard({data,generate}){
 const m=month(),inv=data.invoices.filter(i=>i.billing_month===m),billed=inv.reduce((s,i)=>s+Number(i.total),0),paid=data.payments.filter(p=>String(p.payment_date).startsWith(m.slice(0,7))).reduce((s,p)=>s+Number(p.amount),0),occupied=data.units.filter(u=>u.status==="occupied").length,vacant=data.units.filter(u=>u.status==="vacant").length;
 const arrears=inv.filter(i=>i.status!=="paid"&&i.status!=="void").reduce((s,i)=>s+Math.max(0,Number(i.total)-data.allocations.filter(a=>a.invoice_id===i.id).reduce((x,a)=>x+Number(a.amount),0)),0);
 const exp=data.expenses.filter(e=>String(e.expense_date).startsWith(m.slice(0,7))).reduce((s,e)=>s+Number(e.amount),0);
 return <><div className="cards"><Card t="Billed this month" v={money(billed)}/><Card t="Collected" v={money(paid)}/><Card t="Outstanding" v={money(arrears)}/><Card t="Occupancy" v={(data.units.length?Math.round(occupied/data.units.length*100):0)+"%"} sub={vacant+" vacant"}/></div>
 <div className="grid2"><Panel title="Collection status"><div className="metricline"><span>Invoices</span><b>{inv.length}</b></div><div className="metricline"><span>Paid</span><b>{inv.filter(x=>x.status==="paid").length}</b></div><div className="metricline"><span>Partial</span><b>{inv.filter(x=>x.status==="partially_paid").length}</b></div><div className="metricline"><span>Overdue</span><b>{inv.filter(x=>x.status!=="paid"&&x.status!=="void"&&x.due_date<today()).length}</b></div></Panel>
 <Panel title="Portfolio"><div className="metricline"><span>Units</span><b>{data.units.length}</b></div><div className="metricline"><span>Tenants</span><b>{data.tenants.filter(t=>t.status==="active").length}</b></div><div className="metricline"><span>Lease alerts ≤ 90 days</span><b>{data.leases.filter(l=>new Date(l.end_date)<=new Date(Date.now()+90*864e5)&&l.renewal_status!=="renewed").length}</b></div><div className="metricline"><span>Owner expenses</span><b>{money(exp)}</b></div></Panel></div>
 <Panel title="Quick actions"><div className="actions"><button onClick={generate}><Receipt/>Run billing</button><button onClick={()=>window.print()}><Printer/>Print dashboard</button></div></Panel></>
}
function Card({t,v,sub}){return <div className="card"><span>{t}</span><strong>{v}</strong>{sub&&<small>{sub}</small>}</div>}
function Panel({title,children,actions}){return <div className="panel"><div className="panelhead"><h2>{title}</h2>{actions}</div>{children}</div>}
function Table({heads,rows,empty="No records yet."}){return <div className="table"><div className="thead">{heads.map(h=><span key={h}>{h}</span>)}</div>{rows.length?rows.map((r,i)=><div className="row" key={i}>{r.map((x,j)=><span key={j}>{x}</span>)}</div>):<div className="empty">{empty}</div>}</div>}

function Tenants({data,property,refresh,act,query}){
 const [open,setOpen]=useState(false),[form,setForm]=useState(blank);
 const units=data.units.filter(u=>u.status!=="maintenance");
 const rows=data.tenants.filter(t=>(t.full_name+" "+t.phone+" "+t.id_number).toLowerCase().includes(query.toLowerCase())).map(t=>{const u=data.units.find(x=>x.id===t.unit_id);const out=data.invoices.filter(i=>i.tenant_id===t.id&&i.status!=="void").reduce((s,i)=>s+Number(i.total),0)-data.allocations.filter(a=>data.invoices.some(i=>i.id===a.invoice_id&&i.tenant_id===t.id)).reduce((s,a)=>s+Number(a.amount),0);return [t.full_name,t.phone,u?.label||"—",money(t.rent||u?.monthly_rent),money(Math.max(0,out)),t.status]});
 async function save(e){e.preventDefault();await act(()=>supabase.from("tenants").insert({...form,property_id:property.id,rent:Number(form.rent||0),deposit:Number(form.deposit||0),service_charge:Number(form.service_charge||0),parking:Number(form.parking||0),extras:Number(form.extras||0),unit_id:form.unit_id||null}),"Tenant added");setForm(blank);setOpen(false)}
 return <><div className="actions"><button onClick={()=>setOpen(!open)}><Plus/>Add tenant</button></div>{open&&<Panel title="New tenant"><form className="formgrid" onSubmit={save}>{[["full_name","Full name"],["phone","Phone"],["id_number","ID / Passport"],["rent","Monthly rent"],["deposit","Deposit"],["service_charge","Service charge"],["parking","Parking"],["extras","Other monthly extras"],["lease_start","Lease start"],["lease_end","Lease end"]].map(([k,l])=><label key={k}>{l}<input type={k.includes("date")||k.includes("start")||k.includes("end")?"date":k==="phone"||k.includes("number")||["rent","deposit","service_charge","parking","extras"].includes(k)?"text":"text"} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Unit<select value={form.unit_id} onChange={e=>setForm({...form,unit_id:e.target.value})}><option value="">Unassigned</option>{units.map(u=><option value={u.id} key={u.id}>{u.label}</option>)}</select></label><div><button>Save tenant</button></div></form></Panel>}<Panel title="Tenant ledger"><Table heads={["Tenant","Phone","Unit","Rent","Outstanding","Status"]} rows={rows}/></Panel></>
}

function Units({data,property,refresh,act,query}){
 const [label,setLabel]=useState(""),[rent,setRent]=useState(""),[status,setStatus]=useState("vacant"),[bed,setBed]=useState("1");
 async function add(e){e.preventDefault();await act(()=>supabase.from("units").insert({property_id:property.id,label,monthly_rent:Number(rent||0),bedrooms:Number(bed),status}),"Unit added");setLabel("");setRent("")}
 return <><Panel title="Add unit"><form className="inlineform" onSubmit={add}><input placeholder="Unit e.g. A-01" value={label} onChange={e=>setLabel(e.target.value)} required/><input placeholder="Monthly rent" value={rent} onChange={e=>setRent(e.target.value)} required/><input type="number" min="0" placeholder="Bedrooms" value={bed} onChange={e=>setBed(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option>vacant</option><option>occupied</option><option>reserved</option><option>maintenance</option></select><button><Plus/>Add</button></form></Panel>
 <Panel title="Vacancy & units"><Table heads={["Unit","Beds","Rent","Status","Tenant"]} rows={data.units.filter(u=>(u.label+" "+u.status).toLowerCase().includes(query.toLowerCase())).map(u=>[u.label,u.bedrooms,money(u.monthly_rent),u.status,data.tenants.find(t=>t.unit_id===u.id&&t.status==="active")?.full_name||"—"])}/></Panel></>
}

function Invoices({data,property,refresh,generate,query}){
 const [monthFilter,setMonthFilter]=useState(month());
 const rows=data.invoices.filter(i=>i.billing_month===monthFilter&&(i.invoice_number+" "+(data.tenants.find(t=>t.id===i.tenant_id)?.full_name||"")).toLowerCase().includes(query.toLowerCase())).map(i=>{const tenant=data.tenants.find(t=>t.id===i.tenant_id),allocated=data.allocations.filter(a=>a.invoice_id===i.id).reduce((s,a)=>s+Number(a.amount),0);return [i.invoice_number||i.id.slice(0,8),tenant?.full_name||"—",fmtDate(i.due_date),money(i.total),money(allocated),money(Math.max(0,Number(i.total)-allocated)),i.status]});
 return <><div className="actions"><input type="month" value={monthFilter.slice(0,7)} onChange={e=>setMonthFilter(e.target.value+"-01")}/><button onClick={generate}><Receipt/>Generate invoices</button><button onClick={()=>window.print()}><Printer/>Print</button></div><Panel title={"Invoices · "+monthFilter.slice(0,7)}><Table heads={["Invoice","Tenant","Due","Total","Paid","Balance","Status"]} rows={rows}/></Panel></>
}

function Payments({data,property,refresh,act,query}){
 const [tenant,setTenant]=useState(""),[amount,setAmount]=useState(""),[date,setDate]=useState(today()),[method,setMethod]=useState("M-Pesa"),[ref,setRef]=useState(""),[phone,setPhone]=useState(""),[invoice,setInvoice]=useState("");
 async function save(e){e.preventDefault();const r=await supabase.rpc("allocate_payment_fifo",{p_property_id:property.id,p_tenant_id:tenant,p_amount:Number(amount),p_payment_date:date,p_method:method,p_reference:ref,p_notes:"Manual payment"});setMessageGlobal(r.error?r.error.message:"Payment recorded and allocated");if(!r.error){setAmount("");setRef("");await refresh()}}
 async function stk(){const res=await fetch("/.netlify/functions/mpesa-stk",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({tenant_id:tenant,amount:Number(amount),phone,invoice_number:invoice})});const j=await res.json();setMessageGlobal(res.ok?"STK Push sent to "+phone:(j.error||"STK failed"))}
 const rows=data.payments.filter(p=>(p.reference+" "+p.method+" "+(data.tenants.find(t=>t.id===p.tenant_id)?.full_name||"")).toLowerCase().includes(query.toLowerCase())).map(p=>[fmtDate(p.payment_date),data.tenants.find(t=>t.id===p.tenant_id)?.full_name||"—",money(p.amount),p.method,p.reference||"—"]);
 return <><Panel title="Record payment"><form className="formgrid"><label>Tenant<select value={tenant} onChange={e=>setTenant(e.target.value)}><option value="">Select tenant</option>{data.tenants.filter(t=>t.status==="active").map(t=><option value={t.id} key={t.id}>{t.full_name}</option>)}</select></label><label>Amount<input type="number" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}><option>M-Pesa</option><option>Bank</option><option>Cash</option><option>Cheque</option></select></label><label>Reference<input value={ref} onChange={e=>setRef(e.target.value)} placeholder="M-Pesa receipt / bank ref"/></label><div><button type="button" onClick={save}><WalletCards/>Record & auto-allocate</button></div></form><div className="subpanel"><h3>Optional M-Pesa STK Push</h3><div className="inlineform"><input placeholder="Tenant phone" value={phone} onChange={e=>setPhone(e.target.value)}/><input placeholder="Invoice number (optional)" value={invoice} onChange={e=>setInvoice(e.target.value)}/><button type="button" onClick={stk} disabled={!tenant||!amount}><Send/>Send STK</button></div></div></Panel><Panel title="Payment history"><Table heads={["Date","Tenant","Amount","Method","Reference"]} rows={rows}/></Panel></>
}
let globalSetter=null;function setMessageGlobal(x){if(globalSetter)globalSetter(x);else alert(x)}

function Utilities({data,property,refresh,act}){
 const [unit,setUnit]=useState(""),[type,setType]=useState("water"),[prev,setPrev]=useState(""),[cur,setCur]=useState(""),[rate,setRate]=useState(""),[date,setDate]=useState(today());
 async function save(e){e.preventDefault();const t=data.tenants.find(x=>x.unit_id===unit&&x.status==="active");await act(()=>supabase.from("meter_readings").insert({property_id:property.id,unit_id:unit,tenant_id:t?.id||null,utility_type:type,reading_date:date,previous_reading:Number(prev),current_reading:Number(cur),rate:Number(rate)}),"Meter reading saved");setPrev("");setCur("")}
 return <><Panel title="Meter reading"><form className="formgrid"><label>Unit<select value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Select unit</option>{data.units.map(u=><option value={u.id} key={u.id}>{u.label}</option>)}</select></label><label>Utility<select value={type} onChange={e=>setType(e.target.value)}><option>water</option><option>electricity</option></select></label><label>Previous<input type="number" value={prev} onChange={e=>setPrev(e.target.value)}/></label><label>Current<input type="number" value={cur} onChange={e=>setCur(e.target.value)}/></label><label>Rate<input type="number" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div><button><Plus/>Save reading</button></div></form></Panel><Panel title="Recent readings"><Table heads={["Date","Unit","Utility","Consumption","Amount"]} rows={data.readings.slice(0,50).map(r=>[fmtDate(r.reading_date),data.units.find(u=>u.id===r.unit_id)?.label||"—",r.utility_type,Number(r.consumption||0),money(r.amount)])}/></Panel></>
}

function Leases({data,property,refresh,act}){
 const [tenant,setTenant]=useState(""),[unit,setUnit]=useState(""),[start,setStart]=useState(today()),[end,setEnd]=useState(""),[rent,setRent]=useState(""),[deposit,setDeposit]=useState(""),[status,setStatus]=useState("pending");
 async function save(e){e.preventDefault();await act(()=>supabase.from("leases").insert({property_id:property.id,tenant_id:tenant,unit_id:unit,start_date:start,end_date:end,monthly_rent:Number(rent),deposit:Number(deposit),renewal_status:status}),"Lease created");}
 return <><Panel title="Create lease"><form className="formgrid"><label>Tenant<select value={tenant} onChange={e=>setTenant(e.target.value)}><option value="">Select</option>{data.tenants.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label><label>Unit<select value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Select</option>{data.units.map(u=><option key={u.id} value={u.id}>{u.label}</option>)}</select></label><label>Start<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End<input type="date" value={end} onChange={e=>setEnd(e.target.value)} required/></label><label>Monthly rent<input type="number" value={rent} onChange={e=>setRent(e.target.value)}/></label><label>Deposit<input type="number" value={deposit} onChange={e=>setDeposit(e.target.value)}/></label><div><button><Plus/>Save lease</button></div></form></Panel><Panel title="Lease runway"><Table heads={["Tenant","Unit","Start","End","Days left","Renewal"]} rows={data.leases.map(l=>{const d=Math.ceil((new Date(l.end_date)-new Date())/864e5);return [data.tenants.find(t=>t.id===l.tenant_id)?.full_name||"—",data.units.find(u=>u.id===l.unit_id)?.label||"—",fmtDate(l.start_date),fmtDate(l.end_date),d<0?"Expired":d,d<=90&&l.renewal_status!=="renewed"?"ACTION":"—"]})}/></Panel></>
}

function Owners({data,property,refresh,act}){
 const [name,setName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[fee,setFee]=useState(""),[owner,setOwner]=useState(""),[amount,setAmount]=useState(""),[cat,setCat]=useState(""),[desc,setDesc]=useState("");
 async function addOwner(e){e.preventDefault();await act(()=>supabase.from("owners").insert({property_id:property.id,name,phone,email,management_fee_percent:Number(fee||0)}),"Owner added");setName("")}
 async function addExp(e){e.preventDefault();await act(()=>supabase.from("owner_expenses").insert({property_id:property.id,owner_id:owner,category:cat,description:desc,amount:Number(amount)}),"Expense recorded")}
 const collected=data.payments.filter(p=>String(p.payment_date).startsWith(month().slice(0,7))).reduce((s,p)=>s+Number(p.amount),0),expenses=data.expenses.filter(e=>String(e.expense_date).startsWith(month().slice(0,7))).reduce((s,e)=>s+Number(e.amount),0);
 return <><div className="grid2"><Panel title="Add owner"><form className="formgrid"><label>Name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Management fee %<input type="number" value={fee} onChange={e=>setFee(e.target.value)}/></label><div><button><Plus/>Save owner</button></div></form></Panel><Panel title="Record owner expense"><form className="formgrid"><label>Owner<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Select</option>{data.owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Category<input value={cat} onChange={e=>setCat(e.target.value)}/></label><label>Description<input value={desc} onChange={e=>setDesc(e.target.value)}/></label><label>Amount<input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></label><div><button onClick={addExp}><Plus/>Save expense</button></div></form></Panel></div><Panel title="Owner statement · current month"><div className="cards small"><Card t="Collected" v={money(collected)}/><Card t="Expenses" v={money(expenses)}/><Card t="Net before fee" v={money(collected-expenses)}/></div><Table heads={["Owner","Fee","Net due estimate"]} rows={data.owners.map(o=>{const f=collected*Number(o.management_fee_percent||0)/100;return [o.name,(o.management_fee_percent||0)+"%",money(collected-expenses-f)]})}/></Panel></>
}

function Reports({data,property}){
 const billed=data.invoices.reduce((s,i)=>s+Number(i.total),0),paid=data.payments.reduce((s,p)=>s+Number(p.amount),0),expenses=data.expenses.reduce((s,e)=>s+Number(e.amount),0),outstanding=data.invoices.filter(i=>i.status!=="void").reduce((s,i)=>s+Number(i.total),0)-data.allocations.reduce((s,a)=>s+Number(a.amount),0);
 const statement=()=>{const html=`<html><head><title>RentFlow Statement</title><style>body{font-family:Arial;padding:30px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:8px}</style></head><body><h1>RentFlow · ${property.name}</h1><p>Generated ${new Date().toLocaleString()}</p><table><tr><th>Metric</th><th>Amount</th></tr><tr><td>Total billed</td><td>${money(billed)}</td></tr><tr><td>Total collected</td><td>${money(paid)}</td></tr><tr><td>Outstanding</td><td>${money(Math.max(0,outstanding))}</td></tr><tr><td>Owner expenses</td><td>${money(expenses)}</td></tr></table></body></html>`;const w=window.open("","_blank");w.document.write(html);w.document.close();w.print()};
 return <><div className="cards"><Card t="Total billed" v={money(billed)}/><Card t="Total collected" v={money(paid)}/><Card t="Outstanding" v={money(Math.max(0,outstanding))}/><Card t="Expenses" v={money(expenses)}/></div><Panel title="Reports"><div className="actions"><button onClick={statement}><Printer/>Print / Save statement as PDF</button><button onClick={()=>window.print()}><Download/>Print report</button></div><p>Use the browser print dialog to save PDF copies of owner statements, tenant statements and operational reports.</p></Panel><Panel title="Lease alerts"><Table heads={["Tenant","Unit","Expiry","Days"]} rows={data.leases.filter(l=>new Date(l.end_date)<=new Date(Date.now()+90*864e5)).map(l=>[data.tenants.find(t=>t.id===l.tenant_id)?.full_name||"—",data.units.find(u=>u.id===l.unit_id)?.label||"—",fmtDate(l.end_date),Math.ceil((new Date(l.end_date)-new Date())/864e5)])}/></Panel></>
}

function Notifications({data,property,refresh,act}){
 const [template,setTemplate]=useState("rent_due"),[message,setMessage]=useState(""),[channel,setChannel]=useState("sms");
 function defaultMsg(t){const inv=data.invoices.filter(i=>i.tenant_id===t.id&&i.billing_month===month())[0];const bal=inv?Number(inv.total)-data.allocations.filter(a=>a.invoice_id===inv.id).reduce((s,a)=>s+Number(a.amount),0):0;return `Hello ${t.full_name}, your RentFlow rent balance for ${month().slice(0,7)} is ${money(bal)}. Please make payment. Thank you.`}
 async function sendAll(){const rec=data.tenants.filter(t=>t.status==="active"&&((channel==="whatsapp"&&t.whatsapp_opt_in)||channel==="sms"&&t.sms_opt_in)).map(t=>({tenant_id:t.id,recipient:t.phone,channel}));const msg=message||"Hello, this is a RentFlow property payment reminder.";const r=await fetch("/.netlify/functions/notifications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({property_id:property.id,template,channel,message:msg,recipients:rec})});const j=await r.json();setMessage(j.error||`Processed ${j.results?.length||0} notifications`);await refresh()}
 return <><Panel title="Tenant notifications"><div className="formgrid"><label>Channel<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="sms">SMS</option><option value="whatsapp">WhatsApp</option></select></label><label>Template<select value={template} onChange={e=>setTemplate(e.target.value)}><option value="rent_due">Rent due</option><option value="arrears">Arrears</option><option value="custom">Custom</option></select></label><label className="wide">Message<textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Custom message. For personalized messages, use tenant-specific sending in a future workflow."/></label><div><button onClick={sendAll}><Send/>Send to opted-in tenants</button></div></div></Panel><Panel title="Notification history"><Table heads={["Date","Channel","Recipient","Template","Status"]} rows={data.notifications.slice(0,50).map(n=>[fmtDate(n.created_at),n.channel,n.recipient,n.template,n.status])}/></Panel></>
}

function SettingsPage({property,data}){return <><Panel title="Property settings"><div className="settings"><div><span>Property</span><b>{property.name}</b></div><div><span>Location</span><b>{property.location}</b></div><div><span>Currency</span><b>{property.currency}</b></div><div><span>Units</span><b>{data.units.length}</b></div><div><span>Monthly billing</span><b>Automated via Netlify scheduled function</b></div><div><span>M-Pesa</span><b>Daraja STK Push available when credentials are configured</b></div></div></Panel><Panel title="Production configuration"><p>Add the following secrets to Netlify: <code>SUPABASE_URL</code>, <code>SUPABASE_SERVICE_ROLE_KEY</code>, <code>MPESA_CONSUMER_KEY</code>, <code>MPESA_CONSUMER_SECRET</code>, <code>MPESA_SHORTCODE</code>, <code>MPESA_PASSKEY</code>, <code>MPESA_CALLBACK_URL</code>, optional <code>MPESA_ENVIRONMENT=production</code>, and optional Twilio variables for SMS/WhatsApp.</p><p className="warning">Never put the Supabase service-role key in Vite frontend variables.</p></Panel></>}

function Auth(){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[signup,setSignup]=useState(false),[error,setError]=useState(""),[sent,setSent]=useState(false);async function submit(e){e.preventDefault();setError("");const r=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error)setError(r.error.message);else if(signup)setSent(true)}return <div className="auth"><div><div className="brand"><Building2/><b>RentFlow</b></div><h1>{signup?"Create your account":"Welcome back"}</h1><p>Secure property management for rent, tenants and owners.</p><form onSubmit={submit}><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" minLength="6" value={password} onChange={e=>setPassword(e.target.value)} required/><button>{signup?"Create account":"Sign in"}</button></form>{sent&&<p className="success">Check your email to confirm your account.</p>}{error&&<p className="error">{error}</p>}<button className="link" onClick={()=>setSignup(!signup)}>{signup?"Already registered? Sign in":"Create a new account"}</button></div></div>}
function Onboarding({user,done}){const[name,setName]=useState(""),[location,setLocation]=useState("Kenya"),[error,setError]=useState("");async function create(e){e.preventDefault();const r=await supabase.from("properties").insert({owner_id:user.id,name,location}).select().single();if(r.error){setError(r.error.message);return}const m=await supabase.from("property_members").upsert({property_id:r.data.id,user_id:user.id,role:"owner"});if(m.error)setError(m.error.message);else done()}return <div className="auth"><div><div className="brand"><Building2/><b>RentFlow</b></div><h1>Set up your property</h1><form onSubmit={create}><input placeholder="Property name" value={name} onChange={e=>setName(e.target.value)} required/><input placeholder="Location" value={location} onChange={e=>setLocation(e.target.value)}/><button>Create property</button></form>{error&&<p className="error">{error}</p>}</div></div>}
function ConfigurationScreen({error}){return <div className="auth"><div><div className="brand"><Building2/><b>RentFlow</b></div><h1>RentFlow is not configured</h1><p>The application loaded, but the Supabase connection is not configured correctly.</p><div className="warning"><b>Netlify environment variables required</b><p><code>VITE_SUPABASE_URL</code><br/><code>VITE_SUPABASE_PUBLISHABLE_KEY</code></p><p>{error}</p></div><button onClick={()=>window.location.reload()}><RefreshCw/>Reload</button></div></div>}
function Landing(){return <div className="landing"><div className="brand"><Building2/><b>RentFlow</b></div><h1>Property management without spreadsheet chaos.</h1><p>Tenants, rent, invoices, payments, utilities, leases and owner reporting in one secure workspace.</p><a href="#signin">Sign in to RentFlow</a></div>}
class StartupErrorBoundary extends React.Component{
 constructor(props){super(props);this.state={error:null}}
 static getDerivedStateFromError(error){return {error}}
 componentDidCatch(error,info){console.error("RentFlow startup error",error,info)}
 render(){
  if(this.state.error)return <div className="auth"><div><div className="brand"><Building2/><b>RentFlow</b></div><h1>RentFlow encountered an error</h1><p>The site loaded, but the application encountered a startup error.</p><div className="warning"><b>Error</b><p>{this.state.error?.message||String(this.state.error)}</p></div><button onClick={()=>window.location.reload()}><RefreshCw/>Reload</button></div></div>;
  return this.props.children;
 }
}
window.addEventListener("error",e=>console.error("RentFlow window error",e.error||e.message));
window.addEventListener("unhandledrejection",e=>console.error("RentFlow promise error",e.reason));
createRoot(document.getElementById("root")).render(<StartupErrorBoundary><App/></StartupErrorBoundary>);
